### ISSUE TITLE
Can't compile  on ubuntu 22.04

### ISSUE THREAD

**Issue by cosismo** [ford-prefect/gst-sync-server#11]
Hi, I can't compile this project in Ubuntu 22.04.
(I am a noob building in C,  so sorry if this is not a project-specific issue, but I search for answers on other sites and cannot find a more general building-related solution.)

./autogen.sh
aclocal: error: couldn't open directory 'common/m4': No such file or directory

mkdir common/m4
./autogen.sh
configure.ac:48: error: required file 'common/Makefile.in' not found
configure.ac:48: error: required file 'common/m4/Makefile.in' not found

**Comment by ford-prefect** [comment]
Thanks for the report, I'll try to move this to meson next week so it's less of a hassle to build.

**Comment by ford-prefect** [comment]
This is fixed now.

**Comment by ford-prefect** [comment]
(moved the build system to `meson` which should be easier to work with in general)

**Comment by cosismo** [comment]
Thank you very much. 
I can compile it now.  I really appreciate your work.

As a reference for fellow  noobs:
#tested on a fresh Ubuntu 22.04 installation

#install  required dependencies
sudo apt install git python3-pip build-essential ninja-build libglib2.0-dev libjson-glib-dev libjson-glib-1.0-0 -y

#preferred installation of meson (Ubuntu 22.04 package doesn't satisfy the required version of meson) 
pip3 install --user meson 

#install gstreamer. Reference: https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c
sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav  gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio -y

#get the code
git clone https://github.com/ford-prefect/gst-sync-server.git

#build
cd gst-sync-server
meson setup build
cd build
ninja
