### ISSUE TITLE
Can this use in panoramic stitch ?

### ISSUE THREAD

**Issue by clancylian** [ford-prefect/gst-sync-server#4]
I have multi devices, and use rtspsrc to get multi live streams, can I use it to sync streams and compose them to a panoramic video stream?

**Comment by ford-prefect** [comment]
This is meant for the opposite in some sense -- to take a single stream and play out to multiple devices.

**Comment by ford-prefect** [comment]
Closing this, but please feel free to reopen if you have any more questions/comments.
