### ISSUE TITLE
Network set-up, video on remote client not playing (Ubuntu 18.04LTS)

### ISSUE THREAD

**Issue by reinzor** [ford-prefect/gst-sync-server#8]
My playlist file:

```
file:///tmp/big_buck_bunny_720p.mp4 -1
```

My server on `192.168.2.24` runs the server with arguments `-f playlist.txt`. Client started on other machine with `-a 192.168.2.24` argument. I see the following output:

```
Added client: gst-sync-client-eba0f419, config {}
```

But the client does not start playing, it only shows a still of the first frame when the video restarts. What am I doing wrong here?

Furthermore I also notice only TCP/IP traffic when the video is paused, starts playing or looped. Is the sync event only sent on changes? Won't the video synchronization be off when you play long video files? How is this handled in the TCP example?

**Comment by ford-prefect** [comment]
Yes, the sync server is only taking care of getting state etc. across. Time sychronisation happens with a `GstNetTimeClock`, which is an NTP-like protocol.

Can you run your client with GST_DEBUG=2 in the environment to see if there's an error while decoding?

**Comment by reinzor** [comment]
Thanks, this makes it more clear. It appears that the `GstNetTimeClock` client could not reach the server. Now the playback is nicely synchronous. I will close this issue.
